### ISSUE TITLE
About wtconv3d

### ISSUE THREAD

**Issue by upchen01** [BGU-CS-VIL/WTConv#10]
Hello author, will wtconv3d be released later

**Comment by shahaffind** [comment]
Hey, thank you for your interest in our work.
We did not experiment with 3D convolutions, so we don't plan on releasing it now (maybe in the future when we test it with relevant networks).
There is another closed issue where someone suggested a code for WTConv3d, which you can look for. Just note that it is not official and not tested, so it might have unexpected issues.
