### ISSUE TITLE
Some problem about Wtconv2d

### ISSUE THREAD

**Issue by 2016WUJI01** [BGU-CS-VIL/WTConv#11]
I use the Wtconv2d to replaced Conv2d in my code.
And there are some problem in :
wtconv/Wtconv2d.py", line 14, in __init__
    assert in_channels == out_channels
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

But i use conv2d is success

**Comment by shahaffind** [comment]
Note that WTConv2d is a depth-wise convolution, you probably try to replace Conv2d that works in a dense manner (groups=1).
You should first replace your conv2d with separable convolutions, then you can replace the depth-wise one with WTConv2d (see #4 ).

Please let me know if it solves it or if you have further issues

**Comment by 2016WUJI01** [comment]
Thanks for your reply !
I use this to replace my conv2d. It works.
`
nn.Sequential(
WTConv2d(in_channels, in_channels, kernel_size=2 * i + 1),
                nn.Conv2d(in_channels,out_channels,kernel_size=1)
)
`

`
nn.Conv2d(in_channels, out_channels, kernel_size=2 * i + 1, padding=i)
`

**Comment by shahaffind** [comment]
Glad to hear :)
