### ISSUE TITLE
RuntimeError: expected scalar type Float but found Half

### ISSUE THREAD

**Issue by 3232731490** [BGU-CS-VIL/WTConv#13]
```python
class WTConv2d(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=5, stride=1, bias=True, wt_levels=1, wt_type='db1'):
        super(WTConv2d, self).__init__()

        assert in_channels == out_channels

        self.in_channels = in_channels
        self.wt_levels = wt_levels
        self.stride = stride
        self.dilation = 1

        self.wt_filter, self.iwt_filter = wavelet.create_wavelet_filter(wt_type, in_channels, in_channels, torch.float)
        self.wt_filter = nn.Parameter(self.wt_filter, requires_grad=False)
        self.iwt_filter = nn.Parameter(self.iwt_filter, requires_grad=False)
        
        self.wt_function = wavelet.wavelet_transform_init(self.wt_filter)
        self.iwt_function = wavelet.inverse_wavelet_transform_init(self.iwt_filter)

        self.base_conv = nn.Conv2d(in_channels, in_channels, kernel_size, padding='same', stride=1, dilation=1, groups=in_channels, bias=bias)
        self.base_scale = _ScaleModule([1,in_channels,1,1])

        self.wavelet_convs = nn.ModuleList(
            [nn.Conv2d(in_channels*4, in_channels*4, kernel_size, padding='same', stride=1, dilation=1, groups=in_channels*4, bias=False,dtype=torch.float32) for _ in range(self.wt_levels)]
        )
        self.wavelet_scale = nn.ModuleList(
            [_ScaleModule([1,in_channels*4,1,1], init_scale=0.1) for _ in range(self.wt_levels)]
        )

        if self.stride > 1:
            self.stride_filter = nn.Parameter(torch.ones(in_channels, 1, 1, 1), requires_grad=False)
            self.do_stride = lambda x_in: F.conv2d(x_in, self.stride_filter, bias=None, stride=self.stride, groups=in_channels)
        else:
            self.do_stride = None

    def forward(self, x):
        x = x.to(torch.float32)
        x_ll_in_levels = []
        x_h_in_levels = []
        shapes_in_levels = []

        curr_x_ll = x

        for i in range(self.wt_levels):
            curr_shape = curr_x_ll.shape
            shapes_in_levels.append(curr_shape)
            if (curr_shape[2] % 2 > 0) or (curr_shape[3] % 2 > 0):
                curr_pads = (0, curr_shape[3] % 2, 0, curr_shape[2] % 2)
                curr_x_ll = F.pad(curr_x_ll, curr_pads)

            curr_x = self.wt_function(curr_x_ll)
            curr_x_ll = curr_x[:,:,0,:,:]
            
            shape_x = curr_x.shape
            curr_x_tag = curr_x.reshape(shape_x[0], shape_x[1] * 4, shape_x[3], shape_x[4])
            curr_x_tag = curr_x_tag.to(torch.float32)
            curr_x_tag = self.wavelet_convs[i](curr_x_tag)
            curr_x_tag = self.wavelet_scale[i](curr_x_tag)
            curr_x_tag = curr_x_tag.reshape(shape_x)

            x_ll_in_levels.append(curr_x_tag[:,:,0,:,:])
            x_h_in_levels.append(curr_x_tag[:,:,1:4,:,:])

        next_x_ll = 0

        for i in range(self.wt_levels-1, -1, -1):
            curr_x_ll = x_ll_in_levels.pop()
            curr_x_h = x_h_in_levels.pop()
            curr_shape = shapes_in_levels.pop()

            curr_x_ll = curr_x_ll + next_x_ll

            curr_x = torch.cat([curr_x_ll.unsqueeze(2), curr_x_h], dim=2)
            next_x_ll = self.iwt_function(curr_x)

            next_x_ll = next_x_ll[:, :, :curr_shape[2], :curr_shape[3]]

        x_tag = next_x_ll
        assert len(x_ll_in_levels) == 0
        
        x = self.base_scale(self.base_conv(x))
        x = x + x_tag
        
        if self.do_stride is not None:
            x = self.do_stride(x)

        return x
```
I want to apply your work to the yolo framework, but I have this problem during training, I have manually converted the data type to float32, but this problem still exists, is the problem caused by the yolo framework or is it something else?
```python
            curr_x_tag = curr_x_tag.to(torch.float32)
            curr_x_tag = self.wavelet_convs[i](curr_x_tag)
```
```
  File "/data/nl/GAIIC2024/ultralytics/nn/modules/custom/WTConv.py", line 62, in forward
    curr_x_tag = self.wavelet_convs[i](curr_x_tag)
  File "/data/nl/miniconda3/envs/mbyolo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data/nl/miniconda3/envs/mbyolo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/nl/miniconda3/envs/mbyolo/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/data/nl/miniconda3/envs/mbyolo/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: expected scalar type Float but found Half
```

**Comment by shahaffind** [comment]
The issue might be due to `amp`, which mixes between Halves and Floats automatically and the gradient from the wavelet function does not support it.
Fortunately, I've updated the wavelet function to avoid a different issue, which I think might solve this.
I see from your code that you use the previous version ([this line is the giveaway](https://github.com/BGU-CS-VIL/WTConv/blob/118265bf70be717c7a21938a77358be1368ea776/wtconv/wtconv2d.py#L25)), so please try to clone the updated version and try again.

Let me know if you still have the issue and I'll see what else I can do :)

**Comment by 20191844308** [comment]
你好,用了新版本还是出现了同样的问题

**Comment by hurrrrrrtui** [comment]
> The issue might be due to `amp`, which mixes between Halves and Floats automatically and the gradient from the wavelet function does not support it. Fortunately, I've updated the wavelet function to avoid a different issue, which I think might solve this. I see from your code that you use the previous version ([this line is the giveaway](https://github.com/BGU-CS-VIL/WTConv/blob/118265bf70be717c7a21938a77358be1368ea776/wtconv/wtconv2d.py#L25)), so please try to clone the updated version and try again (also make sure you remove the float conversions).
> 
> Let me know if you still have the issue and I'll see what else I can do :)

Dear Sir,
There still has this issue when using the updated version. What should I do to fix it?
Error:
  File "D:\OBB\ultralytics_yolov8_obb\ultralytics\nn\modules\conv.py", line 495, in forward
    x = self.depthwise(x)
  File "D:\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\anaconda3\envs\yolov8\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\OBB\ultralytics_yolov8_obb\ultralytics\nn\modules\conv.py", line 466, in forward
    x = self.do_stride(x)
  File "D:\OBB\ultralytics_yolov8_obb\ultralytics\nn\modules\conv.py", line 414, in <lambda>
    self.do_stride = lambda x_in: F.conv2d(x_in, self.stride_filter, bias=None, stride=self.stride,
RuntimeError: expected scalar type Half but found Float
Looking forward to your reply.

**Comment by shahaffind** [comment]
The stride operation here is a trick using conv2d with weights of 1 to mimic a normal stride. This is done because strided convolution in the wavelet domain would not work.
Try replacing the following lines:
https://github.com/BGU-CS-VIL/WTConv/blob/654053f1d004dc75d3e0411aeb7020f3d566ad2c/wtconv/wtconv2d.py#L39-L40
With the following code:
```python
self.do_stride = nn.AvgPool2d(kernel_size=1, stride=stride)
```
It should work similarly (averaging over 1 pixel in each stride instead of multiplying it by 1 using conv2d).
If it works I'll update the code

**Comment by hurrrrrrtui** [comment]
@shahaffind Thanks for your reply. It works! :)

**Comment by shahaffind** [comment]
Great, thanks for letting me know, I'll update the code.
