### ISSUE TITLE
Can pre trained models be published on the Tim library for easy access like other classic networks such as ResNet? 

### ISSUE THREAD

**Issue by SuperJinggg** [BGU-CS-VIL/WTConv#14]
I seem to have encountered difficulties loading the pre trained model, and I would like to call it with one line of code from the Timm library. Thank you!

**Comment by SuperJinggg** [comment]
I only need to use your code for downstream migration training, but there are too many model loading configurations for me to start with. I hope to solve this problem with the following simple code: "timm. create. model('wtconvnext_tiny', pretrained=True, features_only=True)"

**Comment by SuperJinggg** [comment]
It's working, thank you very much. Your work has inspired me a lot. Wavelet convolution is a great job, and I hope you can further study it to bring us even better things.

**Comment by SuperJinggg** [comment]
It's working, thank you very much. Your work has inspired me a lot. Wavelet convolution is a great job, and I hope you can further study it to bring us even better things.

**Comment by shahaffind** [comment]
Thank you for your kind words 🙂
Best of luck with your research

**Comment by SuperJinggg** [comment]
Sorry to bother you again, this warning is a bit annoying. How to lift it` FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path, map_location=device)`

**Comment by shahaffind** [comment]
This is an issue with timm's checkpoint loader.
I checked their updates and they seem to fix it in the latest version.
You can try updating timm and see if it works. I will later do my testing as welp and update the requirements accordingly.

**Comment by shahaffind** [comment]
It is a new error from pytorch 2.4.0, and the warning is in the loading function of the timm library.
You can downgrade pytorch to 2.3.1 until they will fix it.

**Comment by SuperJinggg** [comment]
Thank you！
