### ISSUE TITLE
Why is the accuracy 0 when I train with WTConv-T？

### ISSUE THREAD

**Issue by luerer66** [BGU-CS-VIL/WTConv#15]
Sorry to bother you, I trained WTConv-T according to the given training method, with an accuracy of 0 and no decrease in loss.

**Comment by shahaffind** [comment]
Weird, I've successfully trained it just before uploading the code.

Can you try using the training script with convnext_tiny to see if the problem is with the script or the model?

**Comment by luerer66** [comment]
Thank you for your response. I think it should be my problem.

**Comment by shahaffind** [comment]
Ok, let me know if there are further issues :)
