### ISSUE TITLE
Some warnings

### ISSUE THREAD

**Issue by Lmy0914** [BGU-CS-VIL/WTConv#17]
Hello author! Sorry to bother you!
I use the Wtconv2d to replaced Conv2d in my code, but there are some warnings.
![image](https://github.com/user-attachments/assets/68ee769f-fe05-4bb6-9822-bacd50dba4a4)
![image](https://github.com/user-attachments/assets/bbaca066-0555-4b20-89d8-f8c96c2cf1e2)

**Comment by shahaffind** [comment]
Hey :)
The wt_filter and iwt_filter are constant WT decomposition and reconstruction filters and therefore are set with "require_grad=False".
I never encountered this warning, but it should be ok since they should not be changed (i.e. "optimized")

**Comment by Lmy0914** [comment]
ok,thanks for your reply!

**Comment by shahaffind** [comment]
Sure,  let me know if there are further issues with the training
