### ISSUE TITLE
Error in loading weights of the models

### ISSUE THREAD

**Issue by Giazinga** [BGU-CS-VIL/WTConv#18]
I've got a problem when I try to load the model weights. I have tried with each model (tiny, small and base) and everytime there are some Missing key(s) for the architecture and  Unexpected key(s) in state_dict of the loaded weights.  I downloaded the weights in this repositary, their names are WTConvNeXt_tiny_5_300e_ema.pth, WTConvNeXt_small_5_300e_ema.pth, and WTConvNeXt_base_5_300e_ema.pth.

Any suggestion?

**Comment by shahaffind** [comment]
Did you use the script provided? 
If not, can you share the code you use to load the weights?
Also, please share the error message (which keys are the issue)

**Comment by Giazinga** [comment]
Yes, I use train.py script and I load the weights using "load_checkpoint(model, path_to_weight)" from timm.models package (I've also tried to use torch.load and model.load_state_dict but I got the same error message). 

Here the screen of the error message
![Screenshot 2024-10-08 110354](https://github.com/user-attachments/assets/20e3c4ef-018c-485a-9799-3c463977cc06)

**Comment by shahaffind** [comment]
You seem to be trying to create "convnext_tiny" instead of "wtconvnext_tiny".
Try adding the argument `--model wtconvnext_tiny`

**Comment by Giazinga** [comment]
yes I was using --model convnext_tiny, now with wtconvnext_tiny it seems to work.

Thank you :)
