### ISSUE TITLE
question

### ISSUE THREAD

**Issue by luxxg** [BGU-CS-VIL/WTConv#23]
How is this wavelet convolution used? Is it applied after extracting features from the backbone network, or is it used within the backbone network? If used within the backbone, wouldn't that make the pretrained weights unusable? Thank you for your answer.

**Comment by shahaffind** [comment]
WTConv is designed to replace the depthwise convolutions in existing networks architectures. If you don't have depthwise convs in your backbone, see #4 .
You are correct that the original network's pretrained weights can't be used, we do provided weights for convnext+wtconv
