### ISSUE TITLE
WTConv supports strides, you can use it.

### ISSUE THREAD

**Issue by PGX11** [BGU-CS-VIL/WTConv#24]
Hello, I apologize for interrupting you. I have a question.If conv = nn.Conv2d(in_c, out_c, kernel_size=3, stride=2, padding=1，groups=in_c)，How can I replace it with WTConv?

**Comment by shahaffind** [comment]
Hey, you can pass it the strides parameter normally, eg

```python
conv_dw = WTConv(in_c, in_c, kernel_size=3, stride=2, wt_levels=3)
```

(Also, the layer automatically set the padding parameter)

**Comment by PGX11** [comment]
Thank you for your answer. I would like to ask how the 'groups=in_c' parameter is reflected in the WTConv, and whether the following code can be edited to conv_dw = WTConv(in_c, in_c, kernel_size=3, stride=2, wt_levels=3), without any other modifications?
conv = nn.Conv2d(in_c, out_c, kernel_size=3, stride=2, padding=1,groups=in_c)

**Comment by shahaffind** [comment]
Yes, groups is also set automatically.
If in_c equals out_c you can use the code directly. If not, please refer to #4 .

**Comment by PGX11** [comment]
Thank you very much for your answer. You are a responsible writer.
