### ISSUE TITLE
what's the relations between wtconv‘s levels ,kernel size and input size

### ISSUE THREAD

**Issue by omnipotenttom** [BGU-CS-VIL/WTConv#25]
if inputsize is H x W, ,kernel size is 3, How should I set levels  to achieve a larger receptive field or even a global receptive field?

**Comment by omnipotenttom** [comment]
Thank you for your great work！

**Comment by shahaffind** [comment]
Hey @omnipotenttom 

You can experiment with different settings that achieve a global receptive field. Just remember that you need to have about 2xH and 2xW receptive field for a convolution to be global.
To calculate the receptive field for $\ell$ levels and size $k$ convolution, the receptive field is given by $2^\ell\cdot k$.
So, for example, for 16x16 input, you can use $\ell=4, k=3$ for a receptive field of 48x48, but you can also use $\ell=3, k=5$ for a receptive field of 40x40 which would still be enough.

In the paper, we use ConvNeXt as a baseline architecture, which consists of 4 stages operating on inputs of sizes (considering standard Imagenet-1k) 56x56, 28x28, 14x14, and 7x7. We fixed the kernel size to 5 and set the number of levels to 5, 4, 3, and 2 for receptive fields of 160, 80, 40, and 20, respectively.

**Comment by omnipotenttom** [comment]
You explained it very clearly. Thanks again for your great work!
