### ISSUE TITLE
RuntimeError about tensor shape

### ISSUE THREAD

**Issue by sh1chimiya** [BGU-CS-VIL/WTConv#30]
thank you for your code! But,can you help me solve my problem?
i use 
`self.conv1 = nn.Sequential(
            WTConv2d(in_channel, in_channel, kernel_size=3, stride=stride, wt_levels=2, bias=True, wt_type='db1'),
            nn.Conv2d(in_channel, out_channel, kernel_size=1)
        )`
change
`self.conv1 = nn.Conv2d(in_channels=in_channel, out_channels=out_channel, kernel_size=3, padding=1, stride=stride, bias=False)`
in resnet-basicblock
get an error
![image](https://github.com/user-attachments/assets/5fe7a41d-b089-4847-b7b8-d38315d6c341)

**Comment by shahaffind** [comment]
That is weird. The number of elements in the output tensor seems to be half of what is required for the shape.
Can you debug and see the shape of the x before and after the line:
https://github.com/BGU-CS-VIL/WTConv/blob/fa3acfa0b283e98ff0e201ab5eadb4d083dffa16/wtconv/util/wavelet.py#L32

(also check the filters shape)

**Comment by sh1chimiya** [comment]
> That is weird. The number of elements in the output tensor seems to be half of what is required for the shape. Can you debug and see the shape of the x before and after the line:
> 
> https://github.com/BGU-CS-VIL/WTConv/blob/fa3acfa0b283e98ff0e201ab5eadb4d083dffa16/wtconv/util/wavelet.py#L32
> 
> (also check the filters shape)

thank you for your reply.
i mainly print tensor's shape like these pictures and input is tensor[16,3,224,224]
class Resnet
![image](https://github.com/user-attachments/assets/763ff9bd-2a78-4113-a684-72982b4fe818)
class Basicblock
![image](https://github.com/user-attachments/assets/db2743c6-41f1-4efb-9c35-7247667cf937)
and def wavelet_transform
![image](https://github.com/user-attachments/assets/745d8a5b-d1d6-49ff-aaa8-444b04d54257)
and get the output
![image](https://github.com/user-attachments/assets/ff2a14a0-55ee-48ae-95ba-27fac5a19d76)
i think maybe the error occurs from layer2-self.conv2

**Comment by shahaffind** [comment]
It seems like there is an increase in the channel dimension between conv1 to conv2. Did you use the correct in_channels for conv2?

**Comment by sh1chimiya** [comment]
> It seems like there is an increase in the channel dimension between conv1 to conv2. Did you use the correct in_channels for conv2?
> 
> Notice the input dimension is changed from 64 to 128, but the filters dimension is still at 256 (4 x 64) instead of 512 (4 x 128)

thank you for your reply! i think i do set the correct in_channels(layer1 gets right result)
and like what you said, the filters dimension do not change, maybe that makes the error
so could you tell me how to modify the filter correctly?
