### ISSUE TITLE
questions about wt-levels settings

### ISSUE THREAD

**Issue by WKUANEI** [BGU-CS-VIL/WTConv#31]
Excuse me, are there any requirements for the setting of **wt_levels** parameters? Does its setting have anything to do with other parameters? I've read other questions that have set 2 or 3. I don't quite understand

**Comment by shahaffind** [comment]
The levels maximum is according to the layer's input dimension. If after k decompositions, the spatial dimention is 1, it is not possible to do additional decompositions.
Also, if you end up with a 1x1 feature maps after k decompositions, doing a spatial convolution on it is probably not beneficial, so you can use k-1 levels instead.

For example, a 32x32 input after the 4th decomposition will have a spatial dimension of 2x2. An additional decomposition would result in a feature map of size 1x1, so we will consider a maximum of 4 levels.

**Comment by WKUANEI** [comment]
I also want to ask you a question. WTconv replaces depthwise convolution. Do they have the same function? They keep the (channel) dimension unchanged and change H/W.

**Comment by shahaffind** [comment]
In general, yes.
H/W can change through strided convolution which is supported.
