### ISSUE TITLE
UserWarning: Grad strides do not match bucket view strides.

### ISSUE THREAD

**Issue by ZYHzhaoyuhao** [BGU-CS-VIL/WTConv#36]
UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [768, 1, 5, 5], strides() = [25, 1, 5, 1]
bucket_view.sizes() = [768, 1, 5, 5], strides() = [25, 25, 5, 1] (Triggered internally at ../torch/csrc/distributed/c10d/reducer.cpp:327.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

Does this warning have any effect on the performance?

**Comment by shahaffind** [comment]
I think it's a timm related warning.
See https://github.com/huggingface/pytorch-image-models/issues/2147
