### ISSUE TITLE
Will you release the code for Semantic Segmentation?

### ISSUE THREAD

**Issue by chentao2016** [BGU-CS-VIL/WTConv#8]
Will you release the code for Semantic Segmentation?  I am interested in the downstream tasks.

**Comment by shahaffind** [comment]
We used the mmsegmentation library (https://github.com/open-mmlab/mmsegmentation).

We've used an older version of the library (pre-1.0), so we are working on modifying our code to fit a newer version and ensuring it runs without issues.

We will release the configs and trained weights once the transition to the newer version is complete.

**Comment by shahaffind** [comment]
Hey, the MMSegmentation related code was released, the models will be uploaded next, sorry for the delay :)
